### ISSUE TITLE
Diff activation between Theano and TensorFlow.

### ISSUE THREAD

**Issue by since92x** [chuckcho/c3d-keras#2]
Hello! Have you fixed the issue: Activation outputs begin to differ from conv4a layer for Theano and TensorFlow.

**Comment by chuckcho** [comment]
yes. it's gone, and documented: https://github.com/chuckcho/c3d-keras/blob/master/convert_caffe_model.py#L96-L99

**Comment by since92x** [comment]
ok, I have saw it , thank you !
