### ISSUE TITLE
Location of caffe.proto changed

### ISSUE THREAD

**Issue by HartleyTW** [chuckcho/c3d-keras#3]
It seems that the C3D team have changed the folder structure of their Git repo. When getting the caffe.proto file in do_everything.sh, line 13 needs to be:

wget -N https://raw.githubusercontent.com/facebook/C3D/master/C3D-v1.0/src/caffe/proto/caffe.proto

**Comment by chuckcho** [comment]
Indeed. Will fix it soon. Thanks.

**Comment by chuckcho** [comment]
Fixed: https://github.com/chuckcho/c3d-keras/commit/eeec4d3a0a315d30c21ca305f9fa093e6095630f
