### ISSUE TITLE
IndexError:too many indices for array

### ISSUE THREAD

**Issue by hqzxbb** [chuckcho/c3d-keras#4]
file "test_model.py",line 169, in main
    X = vid[start_frame:(start_frame + 16), :, :, :,]
IndexError:too many indices for array

hi, i run the code "python test_model.py" ,then get this. please help me

**Comment by chuckcho** [comment]
Was the video downloaded successfully? what's the size of `vid`, i.e. `vid.shape`?

**Comment by hqzxbb** [comment]
@chuckcho I downloaded the video from youtube, not use download_test_video.sh. And put the video in c3d-keras/  directory. The video name use 6UQIUBS9QHA.mp4.

[Info] Loading model weights -- DONE!
[Info] Loading labels...
Total labels: 487
[Info] Loading a sample video...
('cat:%s', <VideoCapture 0x7fcaca02ec30>)
('vid:%s', [])
('ret:%s', False)
Traceback (most recent call last):
  File "test_model.py", line 228, in <module>
    main()
  File "test_model.py", line 173, in main
    X = vid[start_frame:(start_frame + 16), :, :, :]
IndexError: too many indices for array

The 'ret' value is false, it cause a break then the vid is [ ]. Is the videoCapture's problem cause that?

**Comment by hqzxbb** [comment]
@chuckcho Is there a ffmpeg or gstreamer dependency needed?

**Comment by chuckcho** [comment]
It seems your opencv lib doesn't load a video properly. make sure cv2 can read videos as it should.

**Comment by hqzxbb** [comment]
@chuckcho It is the cv2 can not open the video file. I have searched the issue, but none of the result can solve the problem. I use  ubuntu16.04, opencv3, python2.7. May i know your environment which can run this project successful?

**Comment by chuckcho** [comment]
i use the same system / opencv / python version. please check with opencv documentation.

**Comment by dshahrokhian** [comment]
I am facing the exact same problem.
